[build-system]
requires = ["setuptools>=77", "wheel", "pybind11>=2.10.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zeit-cdts"
version = "0.30.0"
description = "Zeit: Change Detection and Time Series for Python - LandTrendr and CCDC tools"
readme = "README.md"
license = "GPL-2.0-or-later"
license-files = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
dependencies = [
    "numpy",
    "numba>=0.53.0",
    "rasterio",
    "scikit-learn",
    "scipy",
    "dask[array]",
    "xarray",
    "pystac-client",
    "stackstac",
    "geopandas",
    "torch",
    "einops",
    "transformers",
    "planetary-computer",
    "earthengine-api",
    "requests",
    "zarr",
    "rioxarray"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pymannkendall",
    "minisom==2.3.6"
]

[project.urls]
Homepage = "https://github.com/sacridini/zeit-cdts"
Documentation = "https://sacridini.github.io/zeit-cdts/"
Issues = "https://github.com/sacridini/zeit-cdts/issues"

[project.scripts]
zeit = "zeit.cli:main"
